apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-frontend-deployment
  labels:
    app: pos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos-frontend
  template:
    metadata:
      labels:
        app: pos-frontend
    spec:
      containers:
        - name: pos-frontend
          image: kavinduishara/pos-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pos-frontend-service
spec:
  selector:
    app: pos-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort